### ISSUE TITLE
Nosotros: Problema de diseño en responsive

### ISSUE THREAD

**Issue by pmarino2013** [javiertruquin/Desafio-Final#3]
![trukin](https://user-images.githubusercontent.com/35234004/131845005-59023fad-8041-44e7-987f-e489aaf5dc7e.png)

**Comment by javiertruquin** [comment]
Buenas noches
Sabes que estamos re ocupados todos pero ya nos vamos a poner a full.
Queria consultarte esta esta la ultima correccion? resolvemos estos 3
problemas y ya estaria?
muchas gracias.
Saludos

**Comment by pmarino2013** [comment]
Buenas, perdón la demora en responder es más fácil que me manden mensajes por slack. Resolviendo estos issues podemos dar el ok.
Éxitos!
